### ISSUE TITLE
Redesign prototype

### ISSUE THREAD

**Issue by joostf** [cmda-minor-web/intake-tool#19]

**Comment by peppequint** [comment]
New features added to the prototype:

- Top navigation bar with different interactive buttons:
  - Show example, which can be dragged over the screen
  - Hide or show the result what the user is coding
  - Save the code challenge
  - A panel with tips that can be used during the challenge
  - Go to the challenge 
- The code editors can be collapsed or expanded, height of the panel is based on the closed panels

**Comment by joostf** [comment]
Merged branch redesign-prototype into master
