### ISSUE TITLE
Show users bug

### ISSUE THREAD

**Issue by Sanderoost** [cmda-minor-web/intake-tool#20]
At the moment loading the user list takes longer than showing the page which results in no users being shown in the dashboard.
It's solved by simply refreshing the page.

We can fix this issue by waiting until all the users are pushed into the array usersList and then show the page.
I was looking into the async function but couldn't figure it out... 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function

**Comment by joostf** [comment]
This bug is caused by not awaiting async functions.. fixed it in several places
